// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package storetest

import (
	"context"
	"sync"

	"github.com/ONSdigital/dp-graph/v2/models"
)

// DataStoreMock is a mock implementation of datastore.DataStore.
//
//     func TestSomethingThatUsesDataStore(t *testing.T) {
//
//         // make and configure a mocked datastore.DataStore
//         mockedDataStore := &DataStoreMock{
//             GetCodeFunc: func(ctx context.Context, codeListID string, editionID string, codeID string) (*models.Code, error) {
// 	               panic("mock out the GetCode method")
//             },
//             GetCodeDatasetsFunc: func(ctx context.Context, codeListID string, edition string, code string) (*models.Datasets, error) {
// 	               panic("mock out the GetCodeDatasets method")
//             },
//             GetCodeListFunc: func(ctx context.Context, code string) (*models.CodeList, error) {
// 	               panic("mock out the GetCodeList method")
//             },
//             GetCodeListsFunc: func(ctx context.Context, filterBy string) (*models.CodeListResults, error) {
// 	               panic("mock out the GetCodeLists method")
//             },
//             GetCodesFunc: func(ctx context.Context, codeListID string, editionID string) (*models.CodeResults, error) {
// 	               panic("mock out the GetCodes method")
//             },
//             GetEditionFunc: func(ctx context.Context, codeListID string, editionID string) (*models.Edition, error) {
// 	               panic("mock out the GetEdition method")
//             },
//             GetEditionsFunc: func(ctx context.Context, codeListID string) (*models.Editions, error) {
// 	               panic("mock out the GetEditions method")
//             },
//         }
//
//         // use mockedDataStore in code that requires datastore.DataStore
//         // and then make assertions.
//
//     }
type DataStoreMock struct {
	// GetCodeFunc mocks the GetCode method.
	GetCodeFunc func(ctx context.Context, codeListID string, editionID string, codeID string) (*models.Code, error)

	// GetCodeDatasetsFunc mocks the GetCodeDatasets method.
	GetCodeDatasetsFunc func(ctx context.Context, codeListID string, edition string, code string) (*models.Datasets, error)

	// GetCodeListFunc mocks the GetCodeList method.
	GetCodeListFunc func(ctx context.Context, code string) (*models.CodeList, error)

	// GetCodeListsFunc mocks the GetCodeLists method.
	GetCodeListsFunc func(ctx context.Context, filterBy string) (*models.CodeListResults, error)

	// GetCodesFunc mocks the GetCodes method.
	GetCodesFunc func(ctx context.Context, codeListID string, editionID string) (*models.CodeResults, error)

	// GetEditionFunc mocks the GetEdition method.
	GetEditionFunc func(ctx context.Context, codeListID string, editionID string) (*models.Edition, error)

	// GetEditionsFunc mocks the GetEditions method.
	GetEditionsFunc func(ctx context.Context, codeListID string) (*models.Editions, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetCode holds details about calls to the GetCode method.
		GetCode []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CodeListID is the codeListID argument value.
			CodeListID string
			// EditionID is the editionID argument value.
			EditionID string
			// CodeID is the codeID argument value.
			CodeID string
		}
		// GetCodeDatasets holds details about calls to the GetCodeDatasets method.
		GetCodeDatasets []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CodeListID is the codeListID argument value.
			CodeListID string
			// Edition is the edition argument value.
			Edition string
			// Code is the code argument value.
			Code string
		}
		// GetCodeList holds details about calls to the GetCodeList method.
		GetCodeList []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Code is the code argument value.
			Code string
		}
		// GetCodeLists holds details about calls to the GetCodeLists method.
		GetCodeLists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FilterBy is the filterBy argument value.
			FilterBy string
		}
		// GetCodes holds details about calls to the GetCodes method.
		GetCodes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CodeListID is the codeListID argument value.
			CodeListID string
			// EditionID is the editionID argument value.
			EditionID string
		}
		// GetEdition holds details about calls to the GetEdition method.
		GetEdition []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CodeListID is the codeListID argument value.
			CodeListID string
			// EditionID is the editionID argument value.
			EditionID string
		}
		// GetEditions holds details about calls to the GetEditions method.
		GetEditions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CodeListID is the codeListID argument value.
			CodeListID string
		}
	}
	lockGetCode         sync.RWMutex
	lockGetCodeDatasets sync.RWMutex
	lockGetCodeList     sync.RWMutex
	lockGetCodeLists    sync.RWMutex
	lockGetCodes        sync.RWMutex
	lockGetEdition      sync.RWMutex
	lockGetEditions     sync.RWMutex
}

// GetCode calls GetCodeFunc.
func (mock *DataStoreMock) GetCode(ctx context.Context, codeListID string, editionID string, codeID string) (*models.Code, error) {
	if mock.GetCodeFunc == nil {
		panic("DataStoreMock.GetCodeFunc: method is nil but DataStore.GetCode was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		CodeListID string
		EditionID  string
		CodeID     string
	}{
		Ctx:        ctx,
		CodeListID: codeListID,
		EditionID:  editionID,
		CodeID:     codeID,
	}
	mock.lockGetCode.Lock()
	mock.calls.GetCode = append(mock.calls.GetCode, callInfo)
	mock.lockGetCode.Unlock()
	return mock.GetCodeFunc(ctx, codeListID, editionID, codeID)
}

// GetCodeCalls gets all the calls that were made to GetCode.
// Check the length with:
//     len(mockedDataStore.GetCodeCalls())
func (mock *DataStoreMock) GetCodeCalls() []struct {
	Ctx        context.Context
	CodeListID string
	EditionID  string
	CodeID     string
} {
	var calls []struct {
		Ctx        context.Context
		CodeListID string
		EditionID  string
		CodeID     string
	}
	mock.lockGetCode.RLock()
	calls = mock.calls.GetCode
	mock.lockGetCode.RUnlock()
	return calls
}

// GetCodeDatasets calls GetCodeDatasetsFunc.
func (mock *DataStoreMock) GetCodeDatasets(ctx context.Context, codeListID string, edition string, code string) (*models.Datasets, error) {
	if mock.GetCodeDatasetsFunc == nil {
		panic("DataStoreMock.GetCodeDatasetsFunc: method is nil but DataStore.GetCodeDatasets was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		CodeListID string
		Edition    string
		Code       string
	}{
		Ctx:        ctx,
		CodeListID: codeListID,
		Edition:    edition,
		Code:       code,
	}
	mock.lockGetCodeDatasets.Lock()
	mock.calls.GetCodeDatasets = append(mock.calls.GetCodeDatasets, callInfo)
	mock.lockGetCodeDatasets.Unlock()
	return mock.GetCodeDatasetsFunc(ctx, codeListID, edition, code)
}

// GetCodeDatasetsCalls gets all the calls that were made to GetCodeDatasets.
// Check the length with:
//     len(mockedDataStore.GetCodeDatasetsCalls())
func (mock *DataStoreMock) GetCodeDatasetsCalls() []struct {
	Ctx        context.Context
	CodeListID string
	Edition    string
	Code       string
} {
	var calls []struct {
		Ctx        context.Context
		CodeListID string
		Edition    string
		Code       string
	}
	mock.lockGetCodeDatasets.RLock()
	calls = mock.calls.GetCodeDatasets
	mock.lockGetCodeDatasets.RUnlock()
	return calls
}

// GetCodeList calls GetCodeListFunc.
func (mock *DataStoreMock) GetCodeList(ctx context.Context, code string) (*models.CodeList, error) {
	if mock.GetCodeListFunc == nil {
		panic("DataStoreMock.GetCodeListFunc: method is nil but DataStore.GetCodeList was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Code string
	}{
		Ctx:  ctx,
		Code: code,
	}
	mock.lockGetCodeList.Lock()
	mock.calls.GetCodeList = append(mock.calls.GetCodeList, callInfo)
	mock.lockGetCodeList.Unlock()
	return mock.GetCodeListFunc(ctx, code)
}

// GetCodeListCalls gets all the calls that were made to GetCodeList.
// Check the length with:
//     len(mockedDataStore.GetCodeListCalls())
func (mock *DataStoreMock) GetCodeListCalls() []struct {
	Ctx  context.Context
	Code string
} {
	var calls []struct {
		Ctx  context.Context
		Code string
	}
	mock.lockGetCodeList.RLock()
	calls = mock.calls.GetCodeList
	mock.lockGetCodeList.RUnlock()
	return calls
}

// GetCodeLists calls GetCodeListsFunc.
func (mock *DataStoreMock) GetCodeLists(ctx context.Context, filterBy string) (*models.CodeListResults, error) {
	if mock.GetCodeListsFunc == nil {
		panic("DataStoreMock.GetCodeListsFunc: method is nil but DataStore.GetCodeLists was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		FilterBy string
	}{
		Ctx:      ctx,
		FilterBy: filterBy,
	}
	mock.lockGetCodeLists.Lock()
	mock.calls.GetCodeLists = append(mock.calls.GetCodeLists, callInfo)
	mock.lockGetCodeLists.Unlock()
	return mock.GetCodeListsFunc(ctx, filterBy)
}

// GetCodeListsCalls gets all the calls that were made to GetCodeLists.
// Check the length with:
//     len(mockedDataStore.GetCodeListsCalls())
func (mock *DataStoreMock) GetCodeListsCalls() []struct {
	Ctx      context.Context
	FilterBy string
} {
	var calls []struct {
		Ctx      context.Context
		FilterBy string
	}
	mock.lockGetCodeLists.RLock()
	calls = mock.calls.GetCodeLists
	mock.lockGetCodeLists.RUnlock()
	return calls
}

// GetCodes calls GetCodesFunc.
func (mock *DataStoreMock) GetCodes(ctx context.Context, codeListID string, editionID string) (*models.CodeResults, error) {
	if mock.GetCodesFunc == nil {
		panic("DataStoreMock.GetCodesFunc: method is nil but DataStore.GetCodes was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		CodeListID string
		EditionID  string
	}{
		Ctx:        ctx,
		CodeListID: codeListID,
		EditionID:  editionID,
	}
	mock.lockGetCodes.Lock()
	mock.calls.GetCodes = append(mock.calls.GetCodes, callInfo)
	mock.lockGetCodes.Unlock()
	return mock.GetCodesFunc(ctx, codeListID, editionID)
}

// GetCodesCalls gets all the calls that were made to GetCodes.
// Check the length with:
//     len(mockedDataStore.GetCodesCalls())
func (mock *DataStoreMock) GetCodesCalls() []struct {
	Ctx        context.Context
	CodeListID string
	EditionID  string
} {
	var calls []struct {
		Ctx        context.Context
		CodeListID string
		EditionID  string
	}
	mock.lockGetCodes.RLock()
	calls = mock.calls.GetCodes
	mock.lockGetCodes.RUnlock()
	return calls
}

// GetEdition calls GetEditionFunc.
func (mock *DataStoreMock) GetEdition(ctx context.Context, codeListID string, editionID string) (*models.Edition, error) {
	if mock.GetEditionFunc == nil {
		panic("DataStoreMock.GetEditionFunc: method is nil but DataStore.GetEdition was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		CodeListID string
		EditionID  string
	}{
		Ctx:        ctx,
		CodeListID: codeListID,
		EditionID:  editionID,
	}
	mock.lockGetEdition.Lock()
	mock.calls.GetEdition = append(mock.calls.GetEdition, callInfo)
	mock.lockGetEdition.Unlock()
	return mock.GetEditionFunc(ctx, codeListID, editionID)
}

// GetEditionCalls gets all the calls that were made to GetEdition.
// Check the length with:
//     len(mockedDataStore.GetEditionCalls())
func (mock *DataStoreMock) GetEditionCalls() []struct {
	Ctx        context.Context
	CodeListID string
	EditionID  string
} {
	var calls []struct {
		Ctx        context.Context
		CodeListID string
		EditionID  string
	}
	mock.lockGetEdition.RLock()
	calls = mock.calls.GetEdition
	mock.lockGetEdition.RUnlock()
	return calls
}

// GetEditions calls GetEditionsFunc.
func (mock *DataStoreMock) GetEditions(ctx context.Context, codeListID string) (*models.Editions, error) {
	if mock.GetEditionsFunc == nil {
		panic("DataStoreMock.GetEditionsFunc: method is nil but DataStore.GetEditions was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		CodeListID string
	}{
		Ctx:        ctx,
		CodeListID: codeListID,
	}
	mock.lockGetEditions.Lock()
	mock.calls.GetEditions = append(mock.calls.GetEditions, callInfo)
	mock.lockGetEditions.Unlock()
	return mock.GetEditionsFunc(ctx, codeListID)
}

// GetEditionsCalls gets all the calls that were made to GetEditions.
// Check the length with:
//     len(mockedDataStore.GetEditionsCalls())
func (mock *DataStoreMock) GetEditionsCalls() []struct {
	Ctx        context.Context
	CodeListID string
} {
	var calls []struct {
		Ctx        context.Context
		CodeListID string
	}
	mock.lockGetEditions.RLock()
	calls = mock.calls.GetEditions
	mock.lockGetEditions.RUnlock()
	return calls
}
