---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.20.5

inputs:
  - name: dp-code-list-api

outputs:
  - name: build

run:
  path: dp-code-list-api/ci/scripts/build.sh
